version: '3.5'
services:
  nginx:
    container_name: nginx-pmanager
    build: ./nginx
    restart: always
    volumes:
      - api_data:/project
      - ./log:/var/log/nginx
    networks:
      - proxy
    depends_on:
      - web
    environment:
      - VIRTUAL_HOST=ray.growtechnologies.com.br
      - VIRTUAL_NETWORK=nginx-proxy
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=ray.growtechnologies.com.br
      - LETSENCRYPT_EMAIL=admin@growtechnologies.com.br

  web:
    container_name: django-pmanager
    build: ./django
    restart: always
    command: uwsgi --ini uwsgi.ini
    volumes:
      - api_data:/project
    networks:
      - proxy
    env_file:
      - ./.env.dev

volumes:
  api_data:


networks:
  proxy:
    external:
      name: nginx-proxy