# Generated by Django 3.1.3 on 2021-08-11 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_auto_20210811_1057'),
        ('gallery', '0002_auto_20201222_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='foto',
            name='fazenda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fazenda_id', to='properties.fazenda'),
        ),
        migrations.AddField(
            model_name='foto',
            name='residencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='residencia_id', to='properties.residencia'),
        ),
        migrations.AddField(
            model_name='foto',
            name='terreno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='terreno_id', to='properties.terreno'),
        ),
        migrations.AlterField(
            model_name='foto',
            name='imovel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='residencia_id', to='properties.imovel'),
        ),
    ]
