# Generated by Django 3.1.3 on 2021-08-11 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_auto_20210811_1057'),
        ('gallery', '0003_auto_20210811_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foto',
            name='imovel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='properties.imovel'),
            preserve_default=False,
        ),
    ]
