# Generated by Django 3.1.3 on 2020-11-11 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Imovel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UF', models.CharField(blank=True, max_length=2, null=True, verbose_name='UF')),
                ('cidade', models.CharField(blank=True, max_length=2, null=True, verbose_name='Cidade')),
                ('cep', models.CharField(blank=True, max_length=10, null=True, verbose_name='CEP')),
                ('nome', models.CharField(blank=True, max_length=10, null=True, verbose_name='Nome')),
                ('logradouro', models.CharField(blank=True, max_length=50, null=True, verbose_name='Logradouro')),
                ('numero', models.PositiveIntegerField(blank=True, null=True, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, max_length=50, null=True, verbose_name='Complemento')),
            ],
            options={
                'verbose_name': 'Imóvel',
                'verbose_name_plural': 'Imóveis',
            },
        ),
        migrations.CreateModel(
            name='Residencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dormitorios', models.PositiveSmallIntegerField(verbose_name='Quantidade de dormitórios')),
                ('suites', models.PositiveSmallIntegerField(verbose_name='Quantidade de suítes')),
                ('lavabos', models.PositiveSmallIntegerField(verbose_name='Quantidade de lavabos')),
                ('banheiros', models.PositiveSmallIntegerField(verbose_name='Quantidade de Banheiros')),
                ('salas', models.PositiveSmallIntegerField(verbose_name='Quantidade de Salas')),
                ('sacadas', models.PositiveSmallIntegerField(verbose_name='Quantidade de Sacadas')),
                ('vagas', models.PositiveSmallIntegerField(verbose_name='Quantidade de vagas para carros')),
                ('cozinhas', models.PositiveSmallIntegerField(verbose_name='Quantidade de cozinhas')),
                ('infra', models.TextField(blank=True, null=True, verbose_name='Infraestrutura')),
                ('outros', models.TextField(blank=True, null=True, verbose_name='Infraestrutura')),
                ('imovel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='properties.imovel')),
            ],
            options={
                'verbose_name': 'Residência',
                'verbose_name_plural': 'Residências',
            },
        ),
    ]
