# Generated by Django 3.1.3 on 2020-11-19 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Terreno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hectares', models.FloatField(blank=True, null=True, verbose_name='Hectares')),
                ('dimencoes', models.TextField(blank=True, null=True, verbose_name='Dimensões')),
                ('loteamento', models.BooleanField(verbose_name='Loteamento')),
                ('casa', models.BooleanField(verbose_name='Possui casa?')),
                ('plano', models.BooleanField(verbose_name='Plano')),
                ('limpo', models.BooleanField(verbose_name='Limpo')),
                ('limpo_texto', models.TextField(blank=True, null=True, verbose_name='Descrição sobre a limpeza do terreno')),
                ('agua', models.BooleanField(verbose_name='Água')),
                ('agua_texto', models.TextField(blank=True, null=True, verbose_name='Descrição Água')),
                ('posicao', models.TextField(blank=True, null=True, verbose_name='Posição solar')),
                ('imovel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='properties.imovel')),
            ],
            options={
                'verbose_name': 'Terreno',
                'verbose_name_plural': 'Terrenos',
            },
        ),
        migrations.CreateModel(
            name='Fazenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hectares', models.FloatField(blank=True, null=True, verbose_name='Hectares')),
                ('dimencoes', models.TextField(blank=True, null=True, verbose_name='Dimensões')),
                ('agua', models.BooleanField(verbose_name='Água')),
                ('agua_texto', models.TextField(blank=True, null=True, verbose_name='Descrição Água')),
                ('energia', models.BooleanField(verbose_name='Energia')),
                ('animais', models.TextField(verbose_name='Criação de animais')),
                ('propriedade', models.TextField(verbose_name='Limpo')),
                ('imovel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='properties.imovel')),
            ],
            options={
                'verbose_name': 'Terreno',
                'verbose_name_plural': 'Terrenos',
            },
        ),
    ]
