# Generated by Django 3.1.3 on 2020-12-04 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_fazenda_terreno'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fazenda',
            options={'verbose_name': 'Fazenda', 'verbose_name_plural': 'Fazenda'},
        ),
        migrations.RemoveField(
            model_name='fazenda',
            name='agua',
        ),
        migrations.RemoveField(
            model_name='fazenda',
            name='agua_texto',
        ),
        migrations.RemoveField(
            model_name='fazenda',
            name='dimencoes',
        ),
        migrations.RemoveField(
            model_name='fazenda',
            name='hectares',
        ),
        migrations.RemoveField(
            model_name='fazenda',
            name='id',
        ),
        migrations.RemoveField(
            model_name='fazenda',
            name='imovel',
        ),
        migrations.AddField(
            model_name='fazenda',
            name='terreno_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='properties.terreno'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fazenda',
            name='propriedade',
            field=models.TextField(verbose_name='Propriedade'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='UF',
            field=models.CharField(default='RS', max_length=2, verbose_name='UF'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='imovel',
            name='cidade',
            field=models.CharField(default='Santa Maria', max_length=50, verbose_name='Cidade'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='imovel',
            name='complemento',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Complemento'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='logradouro',
            field=models.CharField(default='fg', max_length=50, verbose_name='Logradouro'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='imovel',
            name='nome',
            field=models.CharField(default='fddgfd', max_length=100, verbose_name='Nome'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='residencia',
            name='banheiros',
            field=models.PositiveSmallIntegerField(verbose_name='Banheiros'),
        ),
        migrations.AlterField(
            model_name='residencia',
            name='cozinhas',
            field=models.PositiveSmallIntegerField(verbose_name='Cozinhas'),
        ),
        migrations.AlterField(
            model_name='residencia',
            name='dormitorios',
            field=models.PositiveSmallIntegerField(verbose_name='Dormitórios'),
        ),
        migrations.AlterField(
            model_name='residencia',
            name='lavabos',
            field=models.PositiveSmallIntegerField(verbose_name='Lavabos'),
        ),
        migrations.AlterField(
            model_name='residencia',
            name='outros',
            field=models.TextField(blank=True, null=True, verbose_name='Outros'),
        ),
        migrations.AlterField(
            model_name='residencia',
            name='sacadas',
            field=models.PositiveSmallIntegerField(verbose_name='Sacadas'),
        ),
        migrations.AlterField(
            model_name='residencia',
            name='salas',
            field=models.PositiveSmallIntegerField(verbose_name='Salas'),
        ),
        migrations.AlterField(
            model_name='residencia',
            name='suites',
            field=models.PositiveSmallIntegerField(verbose_name='Suítes'),
        ),
        migrations.AlterField(
            model_name='residencia',
            name='vagas',
            field=models.PositiveSmallIntegerField(verbose_name='Vagas para carros'),
        ),
    ]
