# Generated by Django 3.1.3 on 2020-12-14 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
        ('properties', '0003_auto_20201204_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='imovel',
            name='contato',
            field=models.TextField(blank=True, null=True, verbose_name='Contato'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='config.status'),
        ),
    ]
