# Generated by Django 3.1.3 on 2020-12-15 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_auto_20201214_1316'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imovel',
            options={'verbose_name': 'Imóvel', 'verbose_name_plural': '0 - Todos Imóveis'},
        ),
    ]
