# Generated by Django 3.1.3 on 2020-12-22 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_auto_20201215_1301'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='residencia',
            options={'verbose_name': '1 - Residência', 'verbose_name_plural': '1 - Residências'},
        ),
    ]
