# Generated by Django 3.1.3 on 2021-08-11 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_imovel_descricao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imovel',
            options={'verbose_name': 'Imóvel', 'verbose_name_plural': 'Todos Imóveis'},
        ),
        migrations.AlterModelOptions(
            name='residencia',
            options={'verbose_name': 'Residência', 'verbose_name_plural': 'Residências'},
        ),
        migrations.AlterField(
            model_name='imovel',
            name='descricao',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
    ]
